# Site settings
title: Dash Marketing API Documentation
description: Documentation for Dash Marketing Platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dashmarketing.io" # the base hostname & protocol for your site

# GitHub Pages theme
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
